<div class="page-header">
	<i class="fui-document"></i>意见管理 > 意见列表
</div>
<div>
	<table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>序号</th>
          <th>反馈者</th>
          <th>邮箱</th>
          <th>内容</th>
          <th>状态</th>
          <th>创建时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
      	<?php if($page->total_items==0):?>
      	<tr class="none"><td colspan="7">暂无数据</td></tr>
      	<?php else:?>
      	<?php foreach($page->items as $key=>$advice):?>
        <tr>
          <th scope="row"><?php echo $key+1?></th>
          <td><?php echo $advice->name?></td>
          <td><?php echo $advice->email?></td>
          <td><?php echo $advice->content?></td>
          <td><?php echo $advice->is_delete?></td>
          <td><?php echo $advice->created_at?></td>
          <td data-id="<?php echo $advice->id?>">
		          	<button id="del" class="btn btn-danger btn-xs"><span class="fui-trash"></span> 删除</button>
		          </td>
        </tr>
        <?php endforeach;?>
        <?php endif;?>
      </tbody>
    </table>
    <?php if($page->total_pages!=0):?>
    <?php $this->partial('public/page')?>
    <?php endif;?>
</div>
<script type="text/javascript">
$('[id=del]').click(function() {
	var id = $(this).parent().attr('data-id');

	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除建议',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		del(id);
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
});

function del(id) {
	$.ajax({
        type: "POST",
        url: "/admin/advice/delete",
        data: {id:id},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('删除成功');
            	location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}
</script>