<div class="page-header">
	<i class="fa fa-tasks"></i>任务管理 > 任务列表
</div>
<div>
	<div class="alert alert-info alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert"
			aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<strong>今日任务</strong> 暂时没有正在进行的任务.
	</div>
	<div class="row tasks">
		<div class="col-sm-12">
			<div class="form-group">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="搜索任务 ..."
						id="search-query-3" onkeydown="onSearch(this)"> <span class="input-group-btn">
						<button type="submit" class="btn">
							<span class="fui-search"></span>
						</button>
					</span>
				</div>
			</div>
			<?php if($page->total_items==0):?>
			<div class="none">暂无数据</div>
			<?php else:?>
			<ul class="list-group" id="ul-task">
			<?php foreach($page->items as $key=>$task):?>
			<li class="list-group-item">
				<div class="task">
					<span id="title"><?php echo $task->title?></span>
					<span class="right operations" data-id="<?php echo $task->id?>">
						<i  data-toggle="tooltip" data-placement="top" title="编辑" class="fa fa-pencil text-warning" id="edit"></i>
						<i  data-toggle="tooltip" data-placement="top" title="删除" class="fa fa-close text-danger"  id="del" ></i>
						<i data-toggle="tooltip" data-placement="top" title="详情" class="fa fa-bookmark-o text-info" style="display: inline"></i>
					</span>
				</div>
				<p class="task-date">执行时间:<?php echo $task->start_date?>~<?php echo $task->end_date?></p>
				<div class="task-content">
					<?php echo $task->content?>
				</div>
			</li>
			<?php endforeach;?>
			</ul>
			<?php $this->partial('public/page')?>
			<?php endif;?>
		</div>
	</div>
</div>
<script>
$('[id=edit]').click(function() {
	var id = $(this).parent().attr('data-id');
	location.href='/admin/task/edit/'+id;
});
$('[id=del]').click(function() {
	var id = $(this).parent().attr('data-id');

	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除任务',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		del(id);
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
});

function del(id) {
	$.ajax({
        type: "POST",
        url: "/admin/task/delete",
        data: {id:id},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('删除成功');
            	location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}


function onSearch(obj) {
	setTimeout(function(){//因为是即时查询，需要用setTimeout进行延迟，让值写入到input内，再读取 
		var key = obj.value;//获取输入框的值  
		
		$("#ul-task  li").each(function(index){
			var searchText = $(this).find('#title').html();
			if(searchText.match(key)){
				$(this).show();
			}else {
				$(this).hide();
			}
		});
	},1000);//200为延时时间  
}

$(function () {
	 $('[data-toggle="tooltip"]').tooltip();
})
</script>