<div class="container">
	<div class="row">
		<div class="col-sm-8">
			<div class="box">
				<div class="page-header">
					<i class="fa fa-globe text-info"></i> 关于Blog
				</div>
				<p class="indent">完全是基于个人兴趣开发的博客</p>
				
			</div>
			<div class="box">
				<div class="page-header">
					<i class="fa fa-users text-info"></i> 关于Team
				</div>
				<p class="indent">暂时只有一个人...=.=</p>
			</div>
			
			<div class="box">
				<div class="page-header">
					<i class="fa fa-user-plus text-info"></i> 你想加入开发团队？
				</div>
				<p class="indent">非常欢迎.....请联系：</p>
				<p class="indent"><i class="fa fa-qq"></i>774601526</p>
			</div>
		</div>
	</div>
</div>