<div class="banner">
	<div class="content">
		To be or not to be, that's a question.
	</div>
	<a href="">发起提问</a>
</div>
<div class="container">
	<div class="questions">
		<div class="header">问答列表</div>
		<div class="lists">
			<?php if($page->total_items==0):?>
			<div class="none">暂无数据</div>
			<?php else:?>
			<?php foreach ($page->items as $question):?>
			<div class="title">
				<a href="/question/info/<?php echo $question->code?>" class="text-info"><?php echo $question->title?></a>
				<span class="right visible-md-block visible-lg-block"><?php echo $question->getCreatedAt()?></span>
			</div>
			<?php endforeach;?>
			<?php $this->partial('public/page')?>
			<?php endif;?>
		</div>
	</div>
</div>