<link href="/css/cropper.min.css" rel="stylesheet">
<script src="/js/cropper.min.js"></script>
<div class="container">
	<div class="row">
		<div class="col-sm-3">
		<?php $this->view->partial('public/sidebar')?>
	</div>
		<div class="col-sm-9">
			<ol class="breadcrumb">
				<li><a class="text-info" href="/user/article"><span
						class="fui-document"></span> 个人信息管理</a></li>
				<li class="active">修改头像</li>
			</ol>
			<div class="box">

				<div class="form-horizontal">

					<div class="form-group">
						<div class="col-sm-8">
							<div id="uploader" class="wu-example">
								<div id="thelist" class="uploader-list"></div>
								<div class="btns">
								
									<div id="picker">选择图片</div>
									<button style="display: none" id="submitBtn" class="btn btn-primary" onclick="changeHeadimg()">
										保 存 <i class="fa fa-upload"></i>
									</button>
								</div>
								<!--用来存放文件信息-->
								
								<input type="hidden" id="picture">
							</div>

						</div>
					</div>
					

				</div>

			</div>

		</div>
	</div>
</div>
<script>
$(function() {
	uploadHeadimg();
});
function changeHeadimg() {
	var picture = $("#picture");
	if(!picture.val()) {
		alertify.error("请先选择图片");
		return;
	}
	$.ajax({
        type: "POST",
        url: "/user/home/headimg",
        data: {picture:picture.val()},
        dataType:'json',
        success: function(data){
            console.log(data);
            if(data.errNo==0) {
            	alertify.success('头像修改成功');
            	location.href='/user/home';
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}

function uploadHeadimg() {
	var $ = jQuery, $list = $('#thelist'), $btn = $('#ctlBtn'), state = 'pending', ratio = window.devicePixelRatio || 1,

	// 缩略图大小
	thumbnailWidth = 200 * ratio, thumbnailHeight = 200 * ratio,

	uploader;

	uploader = WebUploader.create({
		// 自动上传。
		auto : true,

		// 不压缩image
		resize : false,

		// swf文件路径
		swf : '/swf/Uploader.swf',

		// 文件接收服务端。
		server : '/upload/img',
		compress : {
			 width: 400,
			    height: 400,

			    // 图片质量，只有type为`image/jpeg`的时候才有效。
			    quality: 90,

			    // 是否允许放大，如果想要生成小图的时候不失真，此选项应该设置为false.
			    allowMagnify: false,

			    // 是否允许裁剪。
			    crop: false,

			    // 是否保留头部meta信息。
			    preserveHeaders: true,

			    // 如果发现压缩后文件大小比原来还大，则使用原来图片
			    // 此属性可能会影响图片自动纠正功能
			    noCompressIfLarger: false,

			    // 单位字节，如果图片大小小于此值，不会采用压缩。
			    compressSize: 0
		},

		// 选择文件的按钮。可选。
		// 内部根据当前运行是创建，可能是input元素，也可能是flash.
		pick : '#picker',
		//fileNumLimit: 1, 
		// 只允许选择图片文件。
		accept : {
			title : 'Images',
			extensions : 'gif,jpg,jpeg,bmp,png',
			mimeTypes : 'image/*'
		}
	});

	uploader
			.on('fileQueued',
					function(file) {
						var $li = $('<div id="' + file.id + '">' + '<img>'
								+ '</div>'), $img = $li.find('img');
						$list.html($li);

						// 创建缩略图
						uploader.makeThumb(file, function(error, src) {
							if (error) {
								$img.replaceWith('<span>不能预览</span>');
								return;
							}

							$img.attr('src', src);
							$("#submitBtn").show();
						}, thumbnailWidth, thumbnailHeight);

					});

	// 文件上传过程中创建进度条实时显示。
	uploader
			.on(
					'uploadProgress',
					function(file, percentage) {
						var $li = $('#' + file.id), $percent = $li
								.find('.progress .progress-bar');

						// 避免重复创建
						if (!$percent.length) {
							$percent = $(
									'<div class="progress progress-striped active">'
											+ '<div class="progress-bar" role="progressbar" style="width: 0%">'
											+ '</div>' + '</div>')
									.appendTo($li).find('.progress-bar');
						}

						$li.find('p.state').text('上传中');

						$percent.css('width', percentage * 100 + '%');
					});

	uploader.on('uploadSuccess', function(file, response) {
		var data = $.parseJSON(response._raw);
		if (data.errNo == 0) {
			$("#picture").val(data.path);
			//$list.append("<input type=hidden id=picture value="+data.path+">");
		} else {
			$('#' + file.id).find('p.state').text('上传出错,请重试');
		}

	});

	uploader.on('uploadError', function(file) {
		$('#' + file.id).find('p.state').text('上传出错');
	});

	uploader.on('uploadComplete', function(file) {
		$('#' + file.id).find('.progress').fadeOut();
	});

	uploader.on('all', function(type) {
		if (type === 'startUpload') {
			state = 'uploading';
		} else if (type === 'stopUpload') {
			state = 'paused';
		} else if (type === 'uploadFinished') {
			state = 'done';
		}

		if (state === 'uploading') {
			$btn.text('暂停上传');
		} else {
			$btn.text('开始上传');
		}
	});

	$btn.on('click', function() {
		if (state === 'uploading') {
			uploader.stop();
		} else {
			uploader.upload();
		}
	});
}
</script>