<div class="container">
<div class="row">
	<div class="col-sm-3">
		<?php $this->view->partial('public/sidebar')?>
	</div>
	<div class="col-sm-9">
		<div class="box">
			<div class="header text-info">
				<i class="fa fa-user"></i> 个人信息
				<small class="more">
					<a href="/user/home/info" class="text-info"><span class="fui-info-circle"></span> 详情</a>
				</small>
			</div>
			<div class="row">
				<div class="col-sm-4">
					<span>用户名:<span>hongker</span></span>
				</div>
				<div class="col-sm-4">
					<span>邮箱:<span>774601526@qq.com</span></span>
				</div>
				<div class="col-sm-4">
					<span>地址:<span>中国四川省成都市</span></span>
				</div>
				<div class="col-sm-4">
					<span>年龄:<span>20</span></span>
				</div>
				<div class="col-sm-4">
					<span>性别:<span>男</span></span>
				</div>
			</div>
			
		</div>
		<div class="box">
			<div class="header text-danger">
				<i class="fa fa-gears"></i> 系统公告
				<small class="more">
					<a href="#" class="text-info"><span class="fui-info-circle"></span> 更多</a>
				</small>
			</div>
			<div class="systemArticles">
				<?php if($systemArticles->count()):?>
				<?php foreach($systemArticles as $article):?>
				<div><a href="/article/info/<?php echo $article->id?>"><?php echo $article->title?></a></div>
				<?php endforeach;?>
				<?php else:?>
				<div class="none">暂无数据</div>
				<?php endif;?>
			</div>
		</div>
		<div class="box">
			<div class="header text-primary">
				<i class="fa fa-comments"></i> 最新评论
				<small class="more">
					<a href="#" class="text-info"><span class="fui-info-circle"></span> 更多</a>
				</small>
			</div>
			<div>
				这里是最新评论列表
			</div>
		</div>
	</div>
</div>
</div>