<div class="container">
	<div class="row">
		<div class="col-sm-3">
		<?php $this->view->partial('public/sidebar')?>
	</div>
		<div class="col-sm-9">
			<ol class="breadcrumb">
				<li><a class="text-info" href="/user/article"><span
						class="fui-document"></span> 个人信息管理</a></li>
				<li class="active">信息详情</li>
			</ol>
			<div class="box">
				<div class="row">
					<div class="col-sm-4">
						<img alt="" class="" src="/images/common_user.png">
					</div>
					<div class="col-sm-8">
						<div class="form-horizontal">
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-2 control-label">用户名：</label>
								<div class="col-sm-10">
									<p class="form-control-static">hongker</p>
								</div>
							</div>
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-2 control-label">邮箱：</label>
								<div class="col-sm-10">
									<p class="form-control-static">xiaok2013@live.com</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
