<div class="container">
	<div class="row">
		<div class="col-sm-8">
			<div class="box">
				<div class="page-header contact-header">
					<span class="fui-eye"></span> 联系我们
				</div>
				<div class="form-horizontal">
					<div class="form-group">
						<label for="email" class="col-sm-2 control-label">邮箱：</label>
						<div class="col-sm-4">
							<input type="email" class="form-control" id="email"
								placeholder="请填写您的邮箱">
						</div>
					</div>
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label">姓名：</label>
						<div class="col-sm-4">
							<input type="email" class="form-control" id="name"
								placeholder="请填写您的姓名">
						</div>
					</div>
					<div class="form-group">
						<label for="content" class="col-sm-2 control-label">内容：</label>
						<div class="col-sm-10">
							<textarea rows="8" class="form-control" id="content"
								placeholder="请填写内容"></textarea>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-info btn-sm"><i class="fa fa-upload"></i> 提 交</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="box">
				<div class="page-header contact-header">
					其他
				</div>
				<div>
					<p><i class="fa fa-phone"></i> 152****4913</p>
					<p><span class="fui-mail"></span> <a class="text-info" href="mailto:774601526@qq.com">774601526@qq.com</a></p>
					<p><span class="fui-location"></span> China.Beijing</p>
				</div>
			</div>
		</div>
	</div>
</div>