<!-- This is banner -->
<!-- 
<div class="banner">
	<div class="title" id="title">
		This is Banner Title
	</div>
	<div class="content">
		This is content for banner,Welcome to Join us.
	</div>
</div>
 -->
<div class="header">
<div class="container-bg">
	<div class="item">
		<div class="title">High performance animations powered by greensock.</div>
		<hr>
		<div class="content">
			To be, or not to be,that's a question.
		</div>
	</div>
</div>	
</div>
<div class="container">
	<div class="row ">
		<?php for($i=0;$i<6;$i++):?>
		<div class="col-sm-4 article_rows">
			<div class="article box" >
				<div class="title text-center">This is Article Title</div>
				<div class="content indent">This is Article content,This is Article content,This is Article content,This is Article content,This is Article content</div>
			</div>
		</div>
		<?php endfor;?>
	</div>
</div>
<script type="text/javascript">
<!--
$(function() {
	
});

function testAlert() {
	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除文章',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		alertify.success('删除成功');
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
}


//-->
</script>
