
<div id="wrapper">
	<div class="fullwidthbanner-container">
		<div class="fullwidthbanner">
			<ul>
				<li data-transition="3dcurtain-horizontal" data-slotamount="15" data-masterspeed="300">
					<img src="/images/slides/slide3.jpg" alt="" />									
				</li>
				<li data-transition="3dcurtain-vertical" data-slotamount="15" data-masterspeed="300" data-link="#">
					<img src="/images/slides/slide5.jpg" alt="" />
				</li>
				<li data-transition="papercut" data-slotamount="15" data-masterspeed="300" data-link="#">
					<img src="/images/slides/slide2.jpg" alt="" />
				</li>
				<li data-transition="turnoff" data-slotamount="15" data-masterspeed="300">
					<img src="/images/slides/slide1.jpg" alt="" />
				</li>	
				<li data-transition="flyin" data-slotamount="15" data-masterspeed="300">
					<img src="/images/slides/slide4.jpg" alt="" />	 
				</li>					
			</ul>
		</div>
	</div>
</div>
<div class="container">
	<div class="br"></div>
	<div class="row">
		<div class="col-sm-9">
			<div class="box">
				<?php foreach($articles as $article):?>
				<div class="article_rows">
					<div class="title"><a class="text-info" href="/article/info/<?php echo $article->id?>"><?php echo $article->title?></a></div>
					<div class="notation">作者：<span><?php echo $article->getAuthor()->username?></span>，发布时间：<span><?php echo $article->created_at?></span></div>
					<div class="article-picture">
						<img alt="" src="<?php echo $article->picture?>">
					</div>
					<div class="article_content">
						<p class="indent"><?php echo $article->digest?></p>
					</div>
					<div class="text-left">
						<a href="/article/info/<?php echo $article->id?>" class="btn btn-info ">阅读全文<i class="fa fa-angle-double-right"></i></a>
					</div>
				</div>
				<hr>
				<?php endforeach;?>
			</div>
		</div>
		<div class="col-sm-3"></div>
	</div>
	
	
</div>
<script type="text/javascript" src="/js/jquery.banner.revolution.min.js"></script>
<script type="text/javascript" src="/js/banner.js"></script>
