<div class="container">
<div class="row">
	<div class="col-sm-3">
		<?php $this->view->partial('public/sidebar')?>
	</div>
	<div class="col-sm-9">
		<ol class="breadcrumb">
		  <li><a class="text-info" href="/user/article"><span class="fui-document"></span> 文章管理</a></li>
		  <li class="active">文章列表</li>
		</ol>
		<div class="box">
			<table class="table table-bordered ">
		      <thead>
		        <tr>
		          <th>序号</th>
		          <th>文章标题</th>
		          <th>文章类型</th>
		          <th>发布时间</th>
		          <th>操作</th>
		        </tr>
		      </thead>
		      <tbody>
		      	<?php if($page->total_items==0):?>
		      	<tr class="none"><td colspan="7">暂无数据</td></tr>
		      	<?php else:?>
		      	<?php foreach($page->items as $key=>$article):?>
		        <tr>
		          <th scope="row"><?php echo $key+1?></th>
		          <td><?php echo $article->title?></td>
		          <td><?php echo $article->getType()->name?></td>
		          <td><?php echo substr($article->created_at,2,14)?></td>
		          <td data-id="<?php echo $article->id?>">
		          	<a href="/user/article/info/<?php echo $article->id?>" class="btn btn-info btn-xs"><span class="fui-info-circle"></span> 查看</a>
		          	<a href="/user/article/edit/<?php echo $article->id?>" class="btn btn-success btn-xs"><span class="fui-new"></span> 编辑</a>
		          	<button id="del" class="btn btn-danger btn-xs"><span class="fui-trash"></span> 删除</button>
		          </td>
		        </tr>
		        <?php endforeach;?>
		        <?php endif;?>
		      </tbody>
		    </table>
		    <?php $this->partial('public/page')?>
		    <a href="/user/article/add" class="btn btn-primary">发布文章 <span class="fui-plus"></span></a>
		</div>
	</div>
</div>
</div>
<script type="text/javascript">
$('[id=del]').click(function() {
	var id = $(this).parent().attr('data-id');

	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除文章',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		del(id);
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
});

function del(id) {
	$.ajax({
        type: "POST",
        url: "/user/article/delete",
        data: {id:id},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('删除成功');
            	location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}
</script>