<footer>
	<!-- 
	<section class="top-footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-7">
					<span>Get started in the Blog today.</span>
				</div>
				<div class="col-sm-5 ">
					<a type="btn" href="/register" class="btn btn-embossed btn-primary btn-block register-btn">Create an account</a>
				</div>
			</div>
		</div>
	</section>
	 -->
	<section class="center-footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<span>网站地图</span>
					<ul>
						<li><a>首页</a></li>
						<li><a>列表</a></li>
						<li><a>登录</a></li>
						<li><a>注册</a></li>
					</ul>
				</div>
				<div class="col-sm-4">
					<span>联系方式</span>
					<ul>
						<li><a><i class="fa fa-phone fa-lg"></i> 028-35124567</a></li>
						<li><a><i class="fa fa-envelope-o fa-lg"></i> admin@blog.com</a></li>
					</ul>
				</div>
				<div class="col-sm-4">
					<span>关注我们</span>
					<ul class="atentions">
						<li><a><i class="fa fa-weibo fa-lg"></i></a></li>
						<li><a><i class="fa fa-twitter fa-lg"></i></a></li>
						<li><a><i class="fa fa-qq fa-lg"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</section>
	<section class="bottom-footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-3 text-center">
					© 2015 Linode, LLC
				</div>
				<div class="col-sm-9 text-center">
					Version 1.0
				</div>
			</div>
		</div>
	</section>
</footer>