<div class="box tile">
	<img src="/images/icons/svg/loop.svg" alt="user-headimage"
		class="tile-image">
	<h6 class="">hongker</h6>
	<a class="btn btn-primary btn-large btn-block" href="/user/info/edit"><span class="fui-new"></span> 修改信息</a>
</div>
<div class="user-sidebar">
	<ul>
		<li><a <?php if($controller=='home') echo 'class="active"'?> href="/user/home">个人信息管理</a></li>
		<li><a <?php if($controller=='article') echo 'class="active"'?> href="/user/article">文章管理</a></li>
		<li><a <?php if($controller=='comment') echo 'class="active"'?> href="/user/comment">评论管理</a></li>
		<li><a <?php if($controller=='collect') echo 'class="active"'?> href="/user/collect">收藏管理</a></li>
	</ul>
</div>