<div class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
			</button>
			<a class="navbar-brand" href="#">Web</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#about">Blog</a></li>
				<li><a href="#about">Contact</a></li>
				<li><a href="#about">About</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="/login">Sign in</a></li>
				<li><a href="../navbar/">Sign up</a></li>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
</div>