<div class="container">
	<div class="row">
		<div class="col-sm-3">
		<?php $this->view->partial('public/sidebar')?>
	</div>
		<div class="col-sm-9">
			<ol class="breadcrumb">
				<li><a class="text-info" href="/user/article"><span
						class="fui-document"></span> 评论管理</a></li>
				<li class="active">评论列表</li>
			</ol>
			<?php if($page->total_items==0):?>
			<div class="none">
				暂无数据
			</div>
			<?php else:?>
		    <?php foreach($page->items as $key=>$comment):?>
			<div class="box comment">
				<blockquote>
					<p><?php echo $comment->content?></p>
					<footer class="">
						<a class="text-info" href="/article/info/<?php echo $comment->target?>"><?php echo $comment->getArticle()->title?></a> <cite title="date"><?php echo substr($comment->created_at,0,10)?></cite>
						<div class="text-right" data-id="<?php echo $comment->id?>">
							<a href="#" class="text-info"><i class="fa fa-comments"></i> 回复(<?php echo $comment->getReplies()->count()?>) </a>
							<a id="del" href="javascript:void(0)" class="text-danger"><span class="fui-trash"></span> 删除</a>
						</div>
					</footer>
				</blockquote>
			</div>
			<?php endforeach;?>
			<?php $this->partial('public/page')?>
		    <?php endif;?>
		    
		</div>
	</div>
</div>
<script type="text/javascript">
$('[id=del]').click(function() {
	var id = $(this).parent().attr('data-id');

	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除评论',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '该评论所属回复也将被删除，删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		del(id);
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
});

function del(id) {
	$.ajax({
        type: "POST",
        url: "/user/comment/delete",
        data: {id:id},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('删除成功');
            	location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}
</script>