<div class="page-header">
	<i class="fui-document"></i>问答管理 > 添加问题
</div>
<div>
	<div class="form-horizontal">
					<div class="form-group">
						<label for="title" class="col-sm-2 control-label">问题标题</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" id="title"
								placeholder="请填入文章标题">
						</div>
					</div>
					
					<div class="form-group">
						<label for="inputPassword3" class="col-sm-2 control-label">问题内容</label>
						<div class="col-sm-10">
							<!-- 编辑器源码文件 -->
							<script type="text/javascript" src="/editor/umeditor.config.js"></script>
							<script type="text/javascript" src="/editor/umeditor.min.js"></script>
							<script type="text/javascript" src="/editor/lang/zh-cn/zh-cn.js"></script>
							<script type="text/plain" name="content" id="myEditor"
								style="height: 240px;">
    							在这里输入内容
							</script>
							<script type="text/javascript">
							    //实例化编辑器
							    var um = UM.getEditor('myEditor',{
							    	initialFrameWidth:"100%",
							        });
			    
							</script>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button class="btn btn-info" onclick="addQuestion()">
								提 交 <i class="fa fa-upload"></i>
							</button>
						</div>
					</div>
				</div>
</div>
<script>
function addQuestion() {
	var title = $("#title");
	if(!title.val()) {
		alertify.error("请填入问题标题");
		title.focus();
		return;
	}

	var content = um.getContent();
	
	$.ajax({
        type: "POST",
        url: "/admin/question/add",
        data: {
            title:title.val(),
            content:content
        },
        dataType:'json',
        success: function(data){
            console.log(data);
            if(data.errNo==0) {
            	alertify.success('添加成功');
            	location.href='/admin/question';
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}
</script>