<div class="page-header">
	<i class="fui-document"></i>问答管理 > 问题列表
</div>
<div>
	<table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>序号</th>
          <th>标题</th>
          <th>作者</th>
          <th>答复</th>
          <th>创建时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
      	<?php if($page->total_items==0):?>
      	<tr class="none"><td colspan="6">暂无数据</td></tr>
      	<?php else:?>
      	<?php foreach($page->items as $key=>$question):?>
        <tr>
          <th scope="row"><?php echo $key+1?></th>
          <td><?php echo $question->title?></td>
          <td><?php echo $question->getAuthor()->username?></td>
          <td><?php echo $question->getAnswers()->count()?></td>
          <td><?php echo $question->created_at?></td>
          <td data-id="<?php echo $question->id?>">
		          	<a href="/admin/question/info/<?php echo $question->code?>" class="btn btn-info btn-xs"><span class="fui-info-circle"></span> 查看</a>
		          	<a href="/admin/question/edit/<?php echo $question->id?>" class="btn btn-success btn-xs"><span class="fui-new"></span> 编辑</a>
		          	
		          	<button id="del" class="btn btn-danger btn-xs"><span class="fui-trash"></span> 删除</button>
		          </td>
        </tr>
        <?php endforeach;?>
        <?php endif;?>
      </tbody>
    </table>
    <?php $this->partial('public/page')?>
</div>
<script type="text/javascript">
$('[id=del]').click(function() {
	var id = $(this).parent().attr('data-id');

	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除问题',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		del(id);
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
});

function del(id) {
	$.ajax({
        type: "POST",
        url: "/admin/question/delete",
        data: {id:id},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('删除成功');
            	location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}
</script>