<div class="page-header">
	<span class="fui-gear"></span> 系统配置 > 添加配置
</div>
<div>
	<div class="form-horizontal">
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label">配置名称</label>
						<div class="col-sm-2">
							<input type="text" class="form-control" id="name"
								placeholder="请填入配置名称">
						</div>
					</div>
					<div class="form-group">
						<label for="ckey" class="col-sm-2 control-label">配置键名</label>
						<div class="col-sm-2">
							<input type="text" class="form-control" id="ckey"
								placeholder="请填入配置键名">
						</div>
					</div>
					<div class="form-group">
						<label for="class" class="col-sm-2 control-label">配置键值</label>
						<div class="col-sm-2">
							<select id="cvalue"
								class="form-control select select-primary select-block mbl">
								<option value="0">请选择配置键值</option>
									<option value="1">启用</option>
									<option value="2">停用</option>
								</select>
						</div>
					</div>
					<div class="form-group">
						<label for="description" class="col-sm-2 control-label">配置说明</label>
						<div class="col-sm-8">
							<textarea rows="4" class="form-control" id="description"
								placeholder="请填入配置说明"></textarea>
						</div>
					</div>
					
					
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button class="btn btn-info" onclick="addArticle()">
								提 交 <i class="fa fa-upload"></i>
							</button>
						</div>
					</div>
				</div>
</div>
<script>
$("select").select2({dropdownCssClass: 'dropdown-inverse'});
function addArticle() {
	var title = $("#title");
	if(!title.val()) {
		alertify.error("请填入文章标题");
		title.focus();
		return;
	}

	var digest = $("#digest");
	if(!digest.val()) {
		alertify.error("请填入文章摘要");
		digest.focus();
		return;
	}

	var type = $("#type");
	if(type.val()==0) {
		alertify.error("请选择文章类型");
		type.focus();
		return;
	}

	var picture = $("#picture");
	if(picture.val()==0) {
		alertify.error("请选择封面图片");
		return;
	}

	var content = um.getContent();

	var className = $("#class");
	if(className.val()==0) {
		alertify.error("请选择文章模块");
		className.focus();
		return;
	}
	
	$.ajax({
        type: "POST",
        url: "/user/article/add",
        data: {title:title.val(),digest:digest.val(),type:type.val(),picture:picture.val(),content:content,className:className.val()},
        dataType:'json',
        success: function(data){
            console.log(data);
            if(data.errNo==0) {
            	alertify.success('文章发布成功');
            	location.href='/user/article';
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}


</script>