<div class="page-header">
	<span class="fui-gear"></span> 系统配置 > 修改配置
</div>
<div>
	<div class="form-horizontal">
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label">配置名称</label>
						<div class="col-sm-2">
							<input type="text" class="form-control" id="name"
								placeholder="请填入配置名称" value="<?php echo $config->name?>">
						</div>
					</div>
					<div class="form-group">
						<label for="ckey" class="col-sm-2 control-label">配置键名</label>
						<div class="col-sm-2">
							<input type="text" class="form-control" id="ckey"
								placeholder="请填入配置键名" value="<?php echo $config->ckey?>">
						</div>
					</div>
					<div class="form-group">
						<label for="class" class="col-sm-2 control-label">配置键值</label>
						<div class="col-sm-2">
							<select id="cvalue"
								class="form-control select select-primary select-block mbl">
								<option value="0">请选择配置键值</option>
								<option value="1" <?php if($config->cvalue==1) echo 'selected'?>>启用</option>
								<option value="2" <?php if($config->cvalue==2) echo 'selected'?>>停用</option>
								</select>
						</div>
					</div>
					<div class="form-group">
						<label for="description" class="col-sm-2 control-label">配置说明</label>
						<div class="col-sm-8">
							<textarea rows="4" class="form-control" id="description"
								placeholder="请填入配置说明"><?php echo $config->description?></textarea>
						</div>
					</div>
					
					
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<input type="hidden" value="<?php echo $config->id?>" id="id">
							<button class="btn btn-info" onclick="editConfig()">
								保 存 <i class="fa fa-save"></i>
							</button>
						</div>
					</div>
				</div>
</div>
<script>
$("select").select2({dropdownCssClass: 'dropdown-inverse'});
function editConfig() {
	var name = $("#name");
	if(!name.val()) {
		alertify.error("请填入配置名称");
		name.focus();
		return;
	}

	var ckey = $("#ckey");
	if(!ckey.val()) {
		alertify.error("请填入配置键值");
		ckey.focus();
		return;
	}
	
	var cvalue = $("#cvalue");
	if(cvalue.val()==0) {
		alertify.error("请选择配置键值");
		cvalue.focus();
		return;
	}

	var description = $("#description");
	if(description.val()==0) {
		alertify.error("请填入配置说明");
		description.focus();
		return;
	}

	var id = $("#id");
	
	$.ajax({
        type: "POST",
        url: "/admin/config/edit",
        data: {
        	id : id.val(),
            name : name.val(),
            ckey : ckey.val(),
            cvalue : cvalue.val(),
            description : description.val(),
        },
        dataType:'json',
        success: function(data){
            console.log(data);
            if(data.errNo==0) {
            	alertify.success('修改配置成功');
            	location.href='/admin/config';
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}


</script>