<div class="register-bg">
	<div class="container">
		<div class="register-form-container">

			<form id="registerForm">
				<div id="register-tip" class="text-danger"></div>
				<div class="form-group has-feedback">
					<input type="text" id="username"
						placeholder="请填写您的用户名" class="form-control" /> <span
						class="form-control-feedback fui-user"></span>
				</div>
				<div class="form-group has-feedback">
					<input type="email" id="email"
						placeholder="请填写您的邮箱" class="form-control" /> <span
						class="form-control-feedback fui-mail"></span>
				</div>
				<div class="form-group has-feedback">
					<input type="password" id="password"
						placeholder="请填写您的密码" class="form-control" /> <span
						class="form-control-feedback fui-lock"></span>
				</div>
				<input type="hidden" id="token" data-key="<?php echo $this->security->getTokenKey() ?>"
        value="<?php echo $this->security->getToken() ?>"/>
				<button id="register-btn" class="btn btn-info btn-lg btn-block"
					type="submit">注 册 <i id="loading" class="fa fa-spinner fa-pulse fa-fw margin-bottom"></i></button>
				<a class="login-link text-info" href="/login">已经有帐号？直接登录!</a>
			</form>
		</div>
	</div>
</div>
<script>
$(function() {
	$("#loading").hide();
	$("#registerForm").submit(function(e){
		var registerBtn = $("#register-btn");
		var username = $("#username").val();
		
		if(!username) {
			$("#register-tip").html('*请填写用户名');
			$("#username").focus();
			return false;
		}
		var email = $("#email").val();
		if(!email) {
			$("#register-tip").html('*请填写您的邮箱');
			$("#email").focus();
			return false;
		}
		var password = $("#password").val();
		if(!password) {
			$("#register-tip").html('*请填写您的密码');
			$("#password").focus();
			return false;
		}

		$("#loading").show();
		var token = $("#token");
		var token_key = token.attr('data-key');
		var token_value = token.val();

		$.post(
			"/register/addUser",
			{
				username:username,
				email:email,
				password:password,
				token_key:token_key,
				token_value:token_value
			},
			function(data){
		    var result = $.parseJSON(data);
		    if(result.errNo==0) {
				alert('注册成功');
				//跳转
				location.href='/';
			}else {
				$("#register-tip").html(result.errMsg);
				token.attr('data-key',result.tokenKey);
				token.val(result.tokenVal);
				$("#loading").hide();
			}
		});
		return false;
		
	});
});


</script>
