<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <?php echo Phalcon\Tag::getTitle() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/font-awesome.min.css" rel="stylesheet">
    <!-- Loading Flat UI -->
    <link href="/css/flat-ui.min.css" rel="stylesheet">
    <link href="/css/theme/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/css/alertify.min.css">
    <!-- Loading alertify bootstrap theme -->
    
	<link href="/css/common.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="/css/jPages.css">
	<link href="/css/highlight/default.min.css" rel="stylesheet">
	<link href="/css/highlight/monokai_sublime.css" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
    <script src="/js/jquery.min.js"></script>
  </head>
  <body>
    <?php echo $this->getContent() ?>

    <!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
    
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- 
    <script src="/js/video.js"></script>
     -->
    <script src="/js/flat-ui.min.js"></script>
    <script src="/js/application.js"></script>
    <script src="/js/alertify.min.js"></script>
	<script src="/js/common.js"></script>
	<script src="/js/highlight.min.js"></script>
	<script type="text/javascript">
		//override defaults
		//alertify.defaults.transition = "slide";
		alertify.defaults.theme.ok = "btn btn-info";
		alertify.defaults.theme.cancel = "btn btn-danger";
		alertify.defaults.theme.input = "form-control";
	</script>
  </body>
</html>
