<div class="page-header">
	<i class="fui-document"></i>文章管理 > 文章分类
</div>
<div class="btn-header">
	<button class="btn btn-info btn-sm" id="addType">添加分类 <span class="fui-plus"></span></button>
</div>
<div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>序号</th>
				<th>名称</th>
				<th>状态</th>
				<th>创建时间</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
      	<?php if($page->total_items==0):?>
      	<tr class="none">
				<td colspan="7">暂无数据</td>
			</tr>
      	<?php else:?>
      	<?php foreach($page->items as $key=>$type):?>
        <tr>
				<th scope="row"><?php echo $key+1?></th>
				<td><?php echo $type->name?></td>
				<td><?php echo $type->is_delete?></td>
				<td><?php echo $type->created_at?></td>
				<td data-id="<?php echo $type->id?>">
					<a href="/user/type/edit/<?php echo $type->id?>"
					class="btn btn-success btn-xs"><span class="fui-new"></span> 编辑</a>
					<button id="del" class="btn btn-danger btn-xs">
						<span class="fui-trash"></span> 删除
					</button></td>
			</tr>
        <?php endforeach;?>
        
        <?php endif;?>
      </tbody>
	</table>
	<?php $this->partial('public/page')?>
</div>
<script>
$("#addType").click(function() {
	alertify.prompt('请填入想要添加的分类名称：', '分类名称', 
			function(evt, value){
				addType(value);
	    	}
		).set({
			'title':'添加文章分类',
			'labels': {ok:'确定', cancel:'取消'},
			});
});
function addType(name) {
	if(!name) {
		alertify.error("添加失败，分类名称不能为空");
		return;
	}
	$.ajax({
        type: "POST",
        url: "/admin/type/add",
        data: {name:name},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('添加成功');
            	location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}
$('[id=del]').click(function() {
	var id = $(this).parent().attr('data-id');

	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除分类',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		del(id);
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
});

function del(id) {
	$.ajax({
        type: "POST",
        url: "/admin/type/delete",
        data: {id:id},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('删除成功');
            	//location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}
</script>