<div class="page-header">
	<span class="fui-gear"></span> 用户管理 > 添加用户
</div>
<div>
	<div class="form-horizontal">
					<div class="form-group">
						<label for="username" class="col-sm-2 control-label">用户名：</label>
						<div class="col-sm-3">
							<input type="text" class="form-control" id="username"
								placeholder="请填入新用户的用户名">
						</div>
					</div>
					<div class="form-group">
						<label for="email" class="col-sm-2 control-label">邮箱：</label>
						<div class="col-sm-3">
							<input type="email" class="form-control" id="email"
								placeholder="请填入新用户的邮箱">
						</div>
					</div>
					<div class="form-group">
						<label for="password" class="col-sm-2 control-label">密码：</label>
						<div class="col-sm-3">
							<input type="password" class="form-control" id="password"
								placeholder="请填入新用户的密码">
						</div>
					</div>
					<div class="form-group">
						<label for="type" class="col-sm-2 control-label">用户类型：</label>
						<div class="col-sm-2">
							<select id="type"
								class="form-control select select-primary select-block mbl">
								<option value="0">请选择用户类型</option>
									<option value="1">普通用户</option>
									<option value="2">管理员</option>
								</select>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button class="btn btn-info" onclick="addUser()">
								提 交 <i class="fa fa-upload"></i>
							</button>
						</div>
					</div>
				</div>
</div>
<script>
$("#type").select2({dropdownCssClass: 'dropdown-inverse'});
function addUser() {
	var username = $("#username");
	if(!username.val()) {
		alertify.error("请填入新用户的名称");
		username.focus();
		return;
	}

	var email = $("#email");
	if(!email.val()) {
		alertify.error("请填入新用户的邮箱");
		email.focus();
		return;
	}

	var password = $("#password");
	if(!password.val()) {
		alertify.error("请填入新用户的密码");
		password.focus();
		return;
	}
	
	var type = $("#type");
	if(type.val()==0) {
		alertify.error("请选择用户类型");
		type.focus();
		return;
	}

	$.ajax({
        type: "POST",
        url: "/admin/user/add",
        data: {
            username : username.val(),
            email : email.val(),
            password : password.val(),
            type : type.val(),
        },
        dataType:'json',
        success: function(data){
            console.log(data);
            if(data.errNo==0) {
            	alertify.success('添加用户成功');
            	if(type.val()==1) {
            		location.href='/admin/user';
                }else if(type.val()==2) {
                	location.href='/admin/user/admin';
                }
            	
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}


</script>