<div class="page-header">
	<span class="fui-gear"></span> 用户管理 > 用户列表
</div>
<div>
	<table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>序号</th>
          <th>用户名</th>
          <th>邮箱</th>
          <th>性别</th>
          <th>年龄</th>
          <th>注册时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
      	<?php if($page->total_items==0):?>
      	<tr class="none"><td colspan="7">暂无数据</td></tr>
      	<?php else:?>
      	<?php foreach($page->items as $key=>$user):?>
        <tr>
          <th scope="row"><?php echo $key+1?></th>
          <td><?php echo $user->username?></td>
          <td><?php echo $user->email?></td>
          <td><?php echo $user->getSex()?></td>
          <td><?php echo $user->age?></td>
          <td><?php echo $user->created_at?></td>
          <td data-id="<?php echo $user->id?>">
          	  <a href="/admin/user/info/<?php echo $user->id?>" class="btn btn-info btn-xs"><span class="fui-info-circle"></span> 详情</a>
		      <a href="/admin/user/edit/<?php echo $user->id?>" class="btn btn-success btn-xs"><span class="fui-new"></span> 编辑</a>
		      <button id="del" class="btn btn-danger btn-xs"><span class="fui-trash"></span> 删除</button>
		  </td>
        </tr>
        <?php endforeach;?>
        <?php endif;?>
      </tbody>
    </table>
    <?php $this->partial('public/page')?>
</div>
<script type="text/javascript">
$('[id=del]').click(function() {
	var id = $(this).parent().attr('data-id');

	var closable = alertify.dialog('confirm').setting('closable');
	//grab the dialog instance and set multiple settings at once.
	alertify.dialog('confirm')
	  .set({
		'title':'删除用户',
	    'labels':{ok:'确定', cancel:'取消'},
	    'message': '删除后将不能恢复，确定要删除么？' ,
	    'onok': function(){
	    		del(id);
		    },
	    'oncancel': function(){ alertify.error('取消操作!');}
	  }).show();
});

function del(id) {
	$.ajax({
        type: "POST",
        url: "/admin/config/delete",
        data: {id:id},
        dataType:'json',
        success: function(data){
            if(data.errNo==0) {
            	alertify.success('删除成功');
            	location.reload();
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}

</script>