<div class="page-header">
	<i class="fui-document"></i>文章管理 > 添加文章
</div>
<div>
	<div class="form-horizontal">
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-2 control-label">文章标题</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" id="title"
								placeholder="请填入文章标题">
						</div>
					</div>
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-2 control-label">文章摘要</label>
						<div class="col-sm-8">
							<textarea rows="4" class="form-control" id="digest"
								placeholder="请填入文章摘要"></textarea>
						</div>
					</div>
					<div class="form-group">
						<label for="type" class="col-sm-2 control-label">文章类型</label>
						<div class="col-sm-2">
							<select id="type"
								class="form-control select select-primary select-block mbl">
								<option value="0">请选择文章类型</option>
									<?php foreach ($types as $type):?>
									<option value="<?php echo $type->id?>"><?php echo $type->name?></option>
									<?php endforeach;?>
								</select>
						</div>
					</div>
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-2 control-label">封面图片</label>
						<div class="col-sm-8">
							<div id="uploader" class="wu-example">
								<div class="rows">
								<div class="col-sm-12">
								<div class="btns">
									<div id="picker">选择文件</div>
									<!-- 
									<button id="ctlBtn" class="btn btn-default">开始上传</button>
									 -->
								</div>
								</div>
								<div class="col-sm-12">
								<!--用来存放文件信息-->
								<div id="thelist" class="uploader-list"></div>
								</div>
								<input type="hidden" id="picture">
								</div>
							</div>

						</div>
					</div>
					<div class="form-group">
						<label for="content" class="col-sm-2 control-label">文章内容</label>
						<div class="col-sm-10">
							<!-- 编辑器源码文件 -->
							<script type="text/javascript" src="/editor/umeditor.config.js"></script>
							<script type="text/javascript" src="/editor/umeditor.min.js"></script>
							<script type="text/javascript" src="/editor/lang/zh-cn/zh-cn.js"></script>
							<script type="text/plain" name="content" id="myEditor"
								style="height: 240px;">
    							在这里输入内容
							</script>
							<script type="text/javascript">
							    //实例化编辑器
							    var um = UM.getEditor('myEditor',{
							    	initialFrameWidth:"100%",
							        });
			    
							</script>
						</div>
					</div>
					<div class="form-group">
						<label for="class" class="col-sm-2 control-label">文章模块</label>
						<div class="col-sm-2">
							<select id="class"
								class="form-control select select-primary select-block mbl">
								<option value="0">请选择文章所属模块</option>
									<option value="1">普通文章</option>
									<option value="2">系统公告</option>
								</select>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button class="btn btn-info" onclick="addArticle()">
								提 交 <i class="fa fa-upload"></i>
							</button>
						</div>
					</div>
				</div>
</div>
<script>
$("select").select2({dropdownCssClass: 'dropdown-inverse'});
function addArticle() {
	var title = $("#title");
	if(!title.val()) {
		alertify.error("请填入文章标题");
		title.focus();
		return;
	}

	var digest = $("#digest");
	if(!digest.val()) {
		alertify.error("请填入文章摘要");
		digest.focus();
		return;
	}

	var type = $("#type");
	if(type.val()==0) {
		alertify.error("请选择文章类型");
		type.focus();
		return;
	}

	var picture = $("#picture");
	if(picture.val()==0) {
		alertify.error("请选择封面图片");
		return;
	}

	var content = um.getContent();
	$.ajax({
        type: "POST",
        url: "/user/article/add",
        data: {title:title.val(),digest:digest.val(),type:type.val(),picture:picture.val(),content:content},
        dataType:'json',
        success: function(data){
            console.log(data);
            if(data.errNo==0) {
            	alertify.success('文章发布成功');
            	location.href='/user/article';
            }else {
            	alertify.error(data.errMsg);
            }
        	
        },
    });
}

/******** 实例化上传按钮 **********/

$(function() {
    uploadImg();
});
</script>