<div class="container">
	<div class="row">
		<div class="col-sm-3">
			<div class="box">
				<ul class="types">
					<li><a href="/article"
						class="<?php if($action=='index') echo 'active';?>">全部</a></li>
				<?php foreach ($types as $type):?>
				<li><a href="/article/classify/<?php echo $type->id?>"
						class="<?php if($currentType==$type->id) echo 'active';?>"><?php echo $type->name?></a></li>
				<?php endforeach;?>
			</ul>
				<div class="clear"></div>
			</div>
			<div class="box">
				<blockquote class="blockquote-danger">博客达人</blockquote>
				<div class="user-ranks">
					<?php if(count($users)==0):?>
					<div class="none">暂无数据</div>
					<?php else:?>
					<?php foreach ($users as $user):?>
					<div class="media">
						<div class="media-left media-middle">
							<a href="/user/index/info/<?php echo $user->username?>"> <img class="media-object img-circle" src="<?php echo $user->picture?>" style="width: 64px; height: 64px;">
							</a>
						</div>
						<div class="media-body">
							<p class="media-heading username"><?php echo $user->username?></p>
						</div>
					</div>
					<?php endforeach;?>
					<?php endif;?>
					
				</div>
			</div>
			<div class="box article_ranks">
				<blockquote class="blockquote-primary">今日点击榜</blockquote>
				<?php if(count($day_ranks)==0):?>
				<div class="none">暂无数据</div>
				<?php else:?>
				<?php foreach ($day_ranks as $article):?>
				<div class="media">
					<div class="media-left">
						<a href="/article/info/<?php echo $article->id?>"> <img class="media-object img-circle" src="<?php echo $article->picture?>" style="width: 64px; height: 64px;">
						</a>
					</div>
					<div class="media-body">
						<p class="media-heading"><a class="text-info" href="/article/info/<?php echo $article->id?>"><?php echo $article->title?></a></p>
						<div class="title-footer">
							<span class="view">类型：<span class="count text-danger"><?php echo $article->getType()->name?></span></span>
							<span class="comment">评论：<span class="count text-success"><?php echo $article->getComments()->count()?></span></span>
						</div>
					</div>
				</div>
				<?php endforeach;?>
				<?php endif;?>
			</div>
		</div>
		<div class="col-sm-9">
			<div class="box">
				<div class="row">
			<?php if($page->total_items==0):?>
			<div class="col-sm-12 none">暂无数据</div>
			<?php else:?>
			<?php foreach ($page->items as $article):?>
			<div class="col-sm-12 article">
						<div
							class="col-sm-4 article-left visible-md-block visible-lg-block">
							<a href="/article/info/<?php echo $article->id?>"><img alt=""
								src="<?php echo $article->picture?>"></a>
							<div class="numbers">
								<span class="view">阅读：<span class="count"><?php echo $article->getView()?></span></span>
								<span class="comment">评论：<span class="count"><?php echo $article->getComments()->count()?></span></span>
								<span class="praise">点赞：<span class="count">20</span></span>
							</div>
						</div>
						<div class="col-sm-8 article-right">
							<div class="title">
								<a class="text-info"
									href="/article/info/<?php echo $article->id?>"><?php echo $article->title?></a>
							</div>

							<div class="info">
								<span class="author">作者：<span class="username"><?php echo $article->getAuthor()->username?></span></span>
								<span class="created_at"><?php echo substr($article->created_at,5,11)?></span>
							</div>
							<!-- 仅小屏幕可见 -->
							<div class="picture">
								<a class="visible-xs-block visible-sm-block"
									href="/article/info/<?php echo $article->id?>"><img alt=""
									src="<?php echo $article->picture?>"></a>
							</div>
							<p class="digest"><?php echo $article->digest?></p>
							<!-- 仅小屏幕可见 -->
							<div class="numbers visible-xs-block visible-sm-block">
								<span class="view">阅读：<span class="count"><?php echo $article->getView()?></span></span>
								<span class="comment">评论：<span class="count"><?php echo $article->getComments()->count()?></span></span>
								<span class="praise">点赞：<span class="count">20</span></span>
							</div>
						</div>
					</div>
					<div class="col-sm-12">
						<hr>
					</div>
			<?php endforeach;?>
			<?php $this->partial('public/page')?>
			<?php endif;?>
		</div>
			</div>
		</div>
	</div>
</div>