<div class="container">
<div class="row">
	<div class="col-sm-7">
		<div class="row">
			<?php for($i=1;$i<10;$i++):?>
			<div class="col-sm-12 article">
				<div class="title">this is title</div>
				<p class="content">Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo eget. Excepteur sint occaecat cupidatat non proident, sunt.</p>
			</div>
			<?php endfor;?>
		</div>
	</div>
	<div class="col-sm-5">
		<ul class="types">
			<?php foreach ($types as $type):?>
			<li><a href="/article/classify/<?php echo $type->id?>" class="text-info"><?php echo $type->name?></a></li>
			<?php endforeach;?>
		</ul>
	</div>
</div>
</div>