<div class="container">
	<div class="row">
		<div class="col-sm-9">
			<div class="box">
				<div class="articleInfo">
					<div class="title"><?php echo $article->title?></div>
					<div class="info">
						<span class="author"> 作者:<span class="username"><?php echo $article->author->username?></span>
						</span> <span class="created_at"> 发布于：<span class="date"><?php echo substr($article->created_at,0,10)?></span>
						</span>
						<span class="collect"><a href="javascript:void(0)" onclick="addCollect(<?php echo $article->id?>,1)" class="text-danger">收藏 <i class="fa fa-bookmark-o "></i></a> </span>
					</div>
					<div class="digest">
						<span>摘要：</span><?php echo $article->digest?>
				</div>
					<hr>
					<div class="content">
					<?php echo $article->content?>
				</div>
					<div class="numbers">
						<span class="view">阅读：<span class="count"><?php echo $article->view?></span></span>
						<span class="comment">评论：<span class="count"><?php echo $article->comments->count()?></span></span>
						<span class="praise">点赞：<span class="count">20</span></span>
					</div>
					<hr>
					<?php $this->partial('public/comment')?>
						
				</div>
			</div>
		</div>
	</div>

</div>
<a href="#top" class="back-to-top">Top</a>
<script src="/js/scrollToTop.js"></script>