<div class="login-bg">
	<div class="container">
		<div class="login-form-container">
			<form id="loginForm">
				<div id="login-tip" class="text-danger"></div>
				<div class="form-group has-feedback">
					<input type="text" id="username" placeholder="username"
						class="form-control" /> <span
						class="form-control-feedback fui-user"></span>
				</div>
				<div class="form-group has-feedback">
					<input type="password" id="password" placeholder="password"
						class="form-control" /> <span
						class="form-control-feedback fui-lock"></span>
				</div>
				<input type="hidden" id="token" data-key="<?php echo $this->security->getTokenKey() ?>"
        value="<?php echo $this->security->getToken() ?>"/>
				<button id="login-btn" class="btn btn-primary btn-lg btn-block" type="submit">登 录 <i id="loading" class="fa fa-spinner fa-pulse fa-fw margin-bottom"></i></button>
				<a class="login-link" href="/forget">忘记密码?</a>
				<a class="login-link text-info" href="/register">如果还没有注册，请点这里!</a>
			</form>
		</div>
	</div>
</div>
<script>
$(function() {
	$("#loading").hide();
	$("#loginForm").submit(function(e){
		var loginBtn = $("#login-btn");
		var username = $("#username").val();
		
		if(!username) {
			$("#login-tip").html('*请填写用户名');
			$("#username").focus();
			return false;
		}
		var password = $("#password").val();
		if(!password) {
			$("#login-tip").html('*请填写您的密码');
			$("#password").focus();
			return false;
		}
		$("#loading").show();
		var token = $("#token");
		var token_key = token.attr('data-key');
		var token_value = token.val();

		$.post(
			"/login/check",
			{
				username:username,
				password:password,
				token_key:token_key,
				token_value:token_value
			},
			function(data){
		    var result = $.parseJSON(data);
		    if(result.errNo==0) {
				alertify.success('登录成功');
				//跳转
				location.href='/';
			}else {
				$("#loading").hide();
				$("#login-tip").html(result.errMsg);
			}
		});
		return false;
		
	});
});

</script>